---
- hosts: all
  user: root
  tasks:
    - name: Setup Ansible User
      user:
        name: ansible
        comment: Ansible Management User
        group: wheel

    - name: Copy our ssh key to ansible user
      authorized_key:
        user: ansible
        key: https://github.com/AlexBaranowski.keys
        state: present

    - name: "Ensuring that wheel is able to use sudo without password"
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
